// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: Director.proto

package Director

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vacio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{0}
}

type MontoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valor int64 `protobuf:"varint,1,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *MontoRequest) Reset() {
	*x = MontoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MontoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoRequest) ProtoMessage() {}

func (x *MontoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoRequest.ProtoReflect.Descriptor instead.
func (*MontoRequest) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{1}
}

func (x *MontoRequest) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type IDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{2}
}

func (x *IDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Conectados struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuarios int64 `protobuf:"varint,1,opt,name=usuarios,proto3" json:"usuarios,omitempty"`
}

func (x *Conectados) Reset() {
	*x = Conectados{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conectados) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conectados) ProtoMessage() {}

func (x *Conectados) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conectados.ProtoReflect.Descriptor instead.
func (*Conectados) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{3}
}

func (x *Conectados) GetUsuarios() int64 {
	if x != nil {
		return x.Usuarios
	}
	return 0
}

type Arma struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opcion int64 `protobuf:"varint,1,opt,name=opcion,proto3" json:"opcion,omitempty"`
}

func (x *Arma) Reset() {
	*x = Arma{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arma) ProtoMessage() {}

func (x *Arma) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arma.ProtoReflect.Descriptor instead.
func (*Arma) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{4}
}

func (x *Arma) GetOpcion() int64 {
	if x != nil {
		return x.Opcion
	}
	return 0
}

type Supervivencia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probabilidad int64 `protobuf:"varint,1,opt,name=probabilidad,proto3" json:"probabilidad,omitempty"`
}

func (x *Supervivencia) Reset() {
	*x = Supervivencia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Supervivencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supervivencia) ProtoMessage() {}

func (x *Supervivencia) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supervivencia.ProtoReflect.Descriptor instead.
func (*Supervivencia) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{5}
}

func (x *Supervivencia) GetProbabilidad() int64 {
	if x != nil {
		return x.Probabilidad
	}
	return 0
}

type CaminoElegido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camino string `protobuf:"bytes,1,opt,name=camino,proto3" json:"camino,omitempty"`
}

func (x *CaminoElegido) Reset() {
	*x = CaminoElegido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaminoElegido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaminoElegido) ProtoMessage() {}

func (x *CaminoElegido) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaminoElegido.ProtoReflect.Descriptor instead.
func (*CaminoElegido) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{6}
}

func (x *CaminoElegido) GetCamino() string {
	if x != nil {
		return x.Camino
	}
	return ""
}

type CaminoCorrecto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probabilidad int64 `protobuf:"varint,1,opt,name=probabilidad,proto3" json:"probabilidad,omitempty"`
}

func (x *CaminoCorrecto) Reset() {
	*x = CaminoCorrecto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaminoCorrecto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaminoCorrecto) ProtoMessage() {}

func (x *CaminoCorrecto) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaminoCorrecto.ProtoReflect.Descriptor instead.
func (*CaminoCorrecto) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{7}
}

func (x *CaminoCorrecto) GetProbabilidad() int64 {
	if x != nil {
		return x.Probabilidad
	}
	return 0
}

type Enfrentamiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probabilidad int64 `protobuf:"varint,1,opt,name=probabilidad,proto3" json:"probabilidad,omitempty"`
}

func (x *Enfrentamiento) Reset() {
	*x = Enfrentamiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enfrentamiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enfrentamiento) ProtoMessage() {}

func (x *Enfrentamiento) ProtoReflect() protoreflect.Message {
	mi := &file_Director_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enfrentamiento.ProtoReflect.Descriptor instead.
func (*Enfrentamiento) Descriptor() ([]byte, []int) {
	return file_Director_proto_rawDescGZIP(), []int{8}
}

func (x *Enfrentamiento) GetProbabilidad() int64 {
	if x != nil {
		return x.Probabilidad
	}
	return 0
}

var File_Director_proto protoreflect.FileDescriptor

var file_Director_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x63, 0x69, 0x6f, 0x22,
	0x24, 0x0a, 0x0c, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x1b, 0x0a, 0x09, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x28, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x1e, 0x0a, 0x04,
	0x41, 0x72, 0x6d, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x0d,
	0x53, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x76, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61,
	0x64, 0x22, 0x27, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x45, 0x6c, 0x65, 0x67, 0x69,
	0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x22, 0x34, 0x0a, 0x0e, 0x43, 0x61,
	0x6d, 0x69, 0x6e, 0x6f, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x12, 0x22, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64,
	0x22, 0x34, 0x0a, 0x0e, 0x45, 0x6e, 0x66, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x64,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x32, 0x3a, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x12,
	0x31, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74,
	0x6f, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x61, 0x63,
	0x69, 0x6f, 0x32, 0x43, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x12, 0x35, 0x0a, 0x15, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x72, 0x4d,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x41, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x65, 0x63,
	0x74, 0x61, 0x64, 0x6f, 0x73, 0x12, 0x33, 0x0a, 0x12, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x73, 0x43, 0x6f, 0x6e, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x73, 0x12, 0x0b, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x63, 0x6f, 0x6e, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x73, 0x32, 0x3c, 0x0a, 0x05, 0x50, 0x69,
	0x73, 0x6f, 0x31, 0x12, 0x33, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x64, 0x61, 0x64, 0x41, 0x72, 0x6d, 0x61, 0x12, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41,
	0x72, 0x6d, 0x61, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72,
	0x76, 0x69, 0x76, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x32, 0x50, 0x0a, 0x05, 0x50, 0x69, 0x73, 0x6f,
	0x32, 0x12, 0x47, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61,
	0x64, 0x43, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x12,
	0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x45, 0x6c, 0x65,
	0x67, 0x69, 0x64, 0x6f, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x6d, 0x69,
	0x6e, 0x6f, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x32, 0x47, 0x0a, 0x05, 0x50, 0x69,
	0x73, 0x6f, 0x33, 0x12, 0x3e, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x61, 0x64, 0x45, 0x6e, 0x66, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f,
	0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x14, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x66, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Director_proto_rawDescOnce sync.Once
	file_Director_proto_rawDescData = file_Director_proto_rawDesc
)

func file_Director_proto_rawDescGZIP() []byte {
	file_Director_proto_rawDescOnce.Do(func() {
		file_Director_proto_rawDescData = protoimpl.X.CompressGZIP(file_Director_proto_rawDescData)
	})
	return file_Director_proto_rawDescData
}

var file_Director_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Director_proto_goTypes = []interface{}{
	(*Vacio)(nil),          // 0: grpc.vacio
	(*MontoRequest)(nil),   // 1: grpc.MontoRequest
	(*IDRequest)(nil),      // 2: grpc.IDRequest
	(*Conectados)(nil),     // 3: grpc.conectados
	(*Arma)(nil),           // 4: grpc.Arma
	(*Supervivencia)(nil),  // 5: grpc.Supervivencia
	(*CaminoElegido)(nil),  // 6: grpc.CaminoElegido
	(*CaminoCorrecto)(nil), // 7: grpc.CaminoCorrecto
	(*Enfrentamiento)(nil), // 8: grpc.Enfrentamiento
}
var file_Director_proto_depIdxs = []int32{
	1, // 0: grpc.monto.ConsultarMonto:input_type -> grpc.MontoRequest
	0, // 1: grpc.Mercenario.IdentificarMercenario:input_type -> grpc.vacio
	0, // 2: grpc.Conectados.UsuariosConectados:input_type -> grpc.vacio
	4, // 3: grpc.Piso1.ProbabilidadArma:input_type -> grpc.Arma
	6, // 4: grpc.Piso2.ProbabilidadCaminoCorrecto:input_type -> grpc.CaminoElegido
	0, // 5: grpc.Piso3.ProbabiliadEnfrentamiento:input_type -> grpc.vacio
	0, // 6: grpc.monto.ConsultarMonto:output_type -> grpc.vacio
	2, // 7: grpc.Mercenario.IdentificarMercenario:output_type -> grpc.IDRequest
	3, // 8: grpc.Conectados.UsuariosConectados:output_type -> grpc.conectados
	5, // 9: grpc.Piso1.ProbabilidadArma:output_type -> grpc.Supervivencia
	7, // 10: grpc.Piso2.ProbabilidadCaminoCorrecto:output_type -> grpc.CaminoCorrecto
	8, // 11: grpc.Piso3.ProbabiliadEnfrentamiento:output_type -> grpc.Enfrentamiento
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Director_proto_init() }
func file_Director_proto_init() {
	if File_Director_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Director_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MontoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conectados); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arma); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Supervivencia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaminoElegido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaminoCorrecto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enfrentamiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Director_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_Director_proto_goTypes,
		DependencyIndexes: file_Director_proto_depIdxs,
		MessageInfos:      file_Director_proto_msgTypes,
	}.Build()
	File_Director_proto = out.File
	file_Director_proto_rawDesc = nil
	file_Director_proto_goTypes = nil
	file_Director_proto_depIdxs = nil
}
